import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "books",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
